services:
  - type: web
    name: bookstore-api
    env: docker
    dockerfilePath: Dockerfile  # Sửa lại đường dẫn
    buildCommand: docker build -t bookstore-api .
    startCommand: docker run -p $PORT:8080 bookstore-api  # Đổi port thành 8080
    envVars:
      - key: PORT
        value: 8080
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: APP_UID  # Thêm biến môi trường APP_UID
        value: "1000"
    healthCheckPath: /health
    autoDeploy: true
    plan: free
    region: singapore